### ISSUE TITLE
Non NN Black Box Methods

### ISSUE THREAD

**Issue by firmai** [IBM/Contrastive-Explanation-Method#2]
Any way that other models can be used, like LightGBM?

Thanks, Derek

**Comment by pinyuchen** [comment]
Hi @firmai 
Yes. Please check out the model-agnostic (applies to any black-box model) version of our contrastive explanation method here: https://cloud.ibm.com/docs/services/ai-openscale-icp?topic=ai-openscale-icp-ie-pp-pn

**Comment by firmai** [comment]
Is there any open source solution? I just want to know before I spent unnecessary time developing a solution myself.

**Comment by pinyuchen** [comment]
Not that I am aware of.
