### ISSUE TITLE
CEM for Colored Images

### ISSUE THREAD

**Issue by vikranthjv** [IBM/Contrastive-Explanation-Method#3]
The current implementation works for Black and white images in mnist (by changing 0 to 1 and vice versa). How do we extend this approach for colored images?

**Comment by pinyuchen** [comment]
Hello. We have a follow-up work https://arxiv.org/abs/1905.12698 that describes how to implement CEM for colored images with monotonic attribution functions. You can find a notebook demo here:　https://nbviewer.jupyter.org/github/IBM/AIX360/blob/master/examples/contrastive/CEM-MAF-CelebA.ipynb

**Comment by vikranthjv** [comment]
Thank you. If I understand correctly, the paper mentioned above helps when the colored images have defined attributes. I'm more interested in classification tasks for colored images. Example: Explaining the decision for an image from the imagenet or cifar10 dataset.

**Comment by pinyuchen** [comment]
Hello @vikranth94. You are right that we propose the use of attribute features as well as a plug-in generator to generate meaningful contrastive explanations for color images. Note that the attribute features need not be pre-defined and can be self-learned from the datasets (see the "ISIC Lesion dataset" examples in our paper https://arxiv.org/pdf/1905.12698.pdf). For ImageNet and Cifar10 (and other color image datasets), you can plug in pre-trained generators for your purpose.
