### ISSUE TITLE
Software requirements

### ISSUE THREAD

**Issue by tuananhroman** [IBM/Contrastive-Explanation-Method#5]
Hey guys,

I'm currently trying to setup your repo and struggled with the versioning. Can someone tell me which Python version is required as well as the associated tf version. 
Thanks in advance!

**Comment by chunchentu** [comment]
Hello,

Thanks for being interested in our work. This project is implemented a while ago and based on my memory we used Python 3.3 and Tensorflow 1.6. However, I would suggest to use the most current version and give it a try.
